# Generated by Django 4.0.2 on 2022-02-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_personaldata_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to='management.employee'),
        ),
    ]
