FROM python:3

ENV PYTHONUNBUFFERED=1
ENV DJANGO_DATABASE='docker'

WORKDIR /code
RUN apt update && apt install -y netcat

COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
