services:
    db:
        image: postgres
        volumes:
            - cmgmtvol:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: .
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db

volumes:
    cmgmtvol: # this a named volume
        external: false
